:hivemq-link: https://www.hivemq.com
:hivemq-extension-docs: {hivemq-link}/docs/extensions/latest/
:hivemq-mqtt-toolbox: {hivemq-link}/mqtt-toolbox
:hivemq-support: {hivemq-link}/support/
:hivemq-testcontainer: https://github.com/hivemq/hivemq-testcontainer
:hivemq-mqtt-client: https://github.com/hivemq/hivemq-mqtt-client

= HiveMQ Sparkplug Aware Extension

image:https://img.shields.io/badge/Extension_Type-Public-orange?style=for-the-badge[Extension Type]
image:https://img.shields.io/github/v/release/hivemq/hivemq-sparkplug-aware-extension?style=for-the-badge[GitHub release (latest by date),link=https://github.com/hivemq/hivemq-sparkplug-aware-extension/releases/latest]
image:https://img.shields.io/github/license/hivemq/hivemq-sparkplug-aware-extension?style=for-the-badge&color=brightgreen[GitHub,link=LICENSE]
image:https://img.shields.io/github/workflow/status/hivemq/hivemq-sparkplug-aware-extension/CI%20Check/master?style=for-the-badge[GitHub Workflow Status (branch),link=https://github.com/hivemq/hivemq-sparkplug-aware-extension/actions/workflows/check.yml?query=branch%3Amaster]

== Purpose

This HiveMQ Sparkplug aware extension has the purpose to fulfil the sparkplug specification to work as an Sparkplu Aware Broker.
it registers a PublishInboundInterceptor to forward all Sparkplug BIRTH and DEATH certificates as Retained messages to an additional sparkplug system topic.
The topic structure, and the sparkplug version can be configured.


== Installation

. Clone this repository into a Java 11 Gradle project.
. Execute the Gradle task `hivemqExtensionZip` to build the extension.
. Move the file: `build/hivemq-extension/hivemq-sparkplug-aware-extension-4.8.0.zip` to the directory: `HIVEMQ_HOME/extensions`
. Unzip the file.
. Start HiveMQ.


== Contributing

If you want to contribute to HiveMQ Sparkplug Aware Extension, see the link:CONTRIBUTING.md[contribution guidelines].

== License

HiveMQ Sparkplug Aware Extension is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].
